# Generated by Django 2.0.7 on 2018-07-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0002_auto_20180704_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='characteristics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='descriptor name'),
        ),
    ]
