# Generated by Django 2.0.7 on 2018-07-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0003_auto_20180704_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='starting_link',
            field=models.TextField(blank=True),
        ),
    ]
