# Generated by Django 2.0.7 on 2018-07-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0005_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='systems',
            field=models.CharField(default='cypher', max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='systems',
            field=models.CharField(default='cypher', max_length=100),
        ),
    ]
