# Generated by Django 2.0.7 on 2018-07-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0006_auto_20180704_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='cypher_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='type',
            name='effort',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='type',
            name='intellect_edge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='intellect_pool',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='type',
            name='might_edge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='might_pool',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='type',
            name='speed_edge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='speed_pool',
            field=models.IntegerField(default=10),
        ),
    ]
