# Generated by Django 2.0.7 on 2018-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0007_auto_20180704_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('systems', models.CharField(default='cypher', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Foci',
                'ordering': ['name'],
            },
        ),
    ]
