# Generated by Django 2.0.7 on 2018-07-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0009_focus_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='major_effect',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='focus',
            name='minor_effect',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
