# Generated by Django 2.0.7 on 2018-07-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0010_auto_20180704_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focus',
            name='major_effect',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='minor_effect',
        ),
    ]
