# Generated by Django 2.0.7 on 2018-07-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0012_auto_20180705_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus',
            old_name='details',
            new_name='other_details',
        ),
    ]
