# Generated by Django 2.0.7 on 2018-07-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0014_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
