# Generated by Django 2.0.7 on 2018-07-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0016_focusability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Ability')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Type')),
            ],
            options={
                'verbose_name_plural': 'Type Abilities',
                'ordering': ['tier', 'ability__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='focusability',
            options={'ordering': ['tier', 'ability__name'], 'verbose_name_plural': 'Focus Abilities'},
        ),
    ]
