# Generated by Django 2.0.7 on 2018-07-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0017_auto_20180705_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='pool_points',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='abilities',
            field=models.TextField(blank=True, verbose_name='base abilities'),
        ),
    ]
