# Generated by Django 2.0.7 on 2018-07-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0018_auto_20180706_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
