# Generated by Django 2.0.7 on 2018-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0019_focus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='focus',
            name='slug',
            field=models.SlugField(),
        ),
    ]
