# Generated by Django 2.0.7 on 2018-07-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0020_auto_20180707_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='slug',
            field=models.SlugField(),
        ),
    ]
