# Generated by Django 2.0.7 on 2018-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0021_auto_20180707_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='slug',
            field=models.SlugField(),
        ),
    ]
