# Generated by Django 2.0.7 on 2018-07-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0023_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='genre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
