# Generated by Django 2.0.7 on 2018-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0024_equipment_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
