# Generated by Django 2.0.7 on 2018-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0025_auto_20180707_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
