# Generated by Django 2.0.7 on 2018-07-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0027_auto_20180707_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['genres', 'type', 'base_cost', 'name'], 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
