# Generated by Django 2.0.7 on 2018-07-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0028_auto_20180708_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
