# Generated by Django 2.0.7 on 2018-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0029_equipment_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtle', models.BooleanField()),
                ('level_range', models.CharField(max_length=10)),
                ('effect', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name_plural': 'Equipment'},
        ),
    ]
