# Generated by Django 2.0.7 on 2018-07-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0030_auto_20180709_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cypher',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
