# Generated by Django 2.0.7 on 2018-07-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0031_cypher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cypher',
            name='subtle',
        ),
    ]
