# Generated by Django 2.0.7 on 2018-07-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0032_remove_cypher_subtle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='sourcebook')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='systems',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='systems',
        ),
        migrations.RemoveField(
            model_name='type',
            name='systems',
        ),
    ]
