# Generated by Django 2.0.7 on 2018-07-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0033_auto_20180710_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Sourcebook',
        ),
    ]
