# Generated by Django 2.0.7 on 2018-07-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0034_auto_20180710_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='sourcebook',
            field=models.ManyToManyField(to='cyphercore.Sourcebook'),
        ),
    ]
