# Generated by Django 2.0.7 on 2018-07-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0035_descriptor_sourcebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptor',
            name='sourcebook',
        ),
        migrations.AddField(
            model_name='descriptor',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Sourcebook'),
        ),
    ]
