# Generated by Django 2.0.7 on 2018-07-10 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0036_auto_20180710_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
    ]
