# Generated by Django 2.0.7 on 2018-07-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0037_auto_20180710_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
        migrations.AddField(
            model_name='cypher',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
        migrations.AddField(
            model_name='focus',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
        migrations.AddField(
            model_name='type',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
    ]
