# Generated by Django 2.0.7 on 2018-07-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0038_auto_20180710_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name'], 'verbose_name_plural': 'Abilities'},
        ),
    ]
