# Generated by Django 2.0.7 on 2018-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0040_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Might', 'Might'), ('Speed', 'Speed'), ('Intellect', 'Intellect')], default='Might', max_length=20),
        ),
    ]
