# Generated by Django 2.0.7 on 2018-07-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0043_auto_20180710_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='genres',
        ),
        migrations.AddField(
            model_name='equipment',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Genre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
