# Generated by Django 2.0.7 on 2018-07-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0044_auto_20180710_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook'),
        ),
    ]
