# Generated by Django 2.0.7 on 2018-07-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0045_genre_sourcebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
    ]
