# Generated by Django 2.0.7 on 2018-07-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0047_auto_20180710_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='abilities',
            new_name='base_abilities',
        ),
    ]
