# Generated by Django 2.0.7 on 2018-07-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0048_auto_20180713_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='type',
            new_name='usage',
        ),
        migrations.AddField(
            model_name='type',
            name='abilities',
            field=models.ManyToManyField(through='cyphercore.TypeAbility', to='cyphercore.Ability'),
        ),
        migrations.AlterField(
            model_name='type',
            name='base_abilities',
            field=models.TextField(blank=True),
        ),
    ]
