# Generated by Django 2.0.7 on 2018-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0049_auto_20180713_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='abilities',
            field=models.ManyToManyField(through='cyphercore.FocusAbility', to='cyphercore.Ability'),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
            preserve_default=False,
        ),
    ]
