# Generated by Django 2.0.7 on 2018-07-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0050_auto_20180715_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
