# Generated by Django 2.0.7 on 2018-07-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0051_remove_skill_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_range', models.CharField(max_length=10)),
                ('effect', models.TextField()),
                ('depletion', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Genre')),
                ('sourcebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
