# Generated by Django 2.0.7 on 2018-07-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0052_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='form',
            field=models.TextField(default='form'),
            preserve_default=False,
        ),
    ]
