# Generated by Django 2.0.7 on 2018-07-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0053_artifact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('background', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tier', models.IntegerField(default=1)),
                ('effort', models.IntegerField(default=1)),
                ('cypher_limit', models.IntegerField(default=2)),
                ('money', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('might_current', models.IntegerField(default=10)),
                ('might_pool', models.IntegerField(default=10)),
                ('might_edge', models.IntegerField(default=0)),
                ('speed_current', models.IntegerField(default=10)),
                ('speed_pool', models.IntegerField(default=10)),
                ('speed_edge', models.IntegerField(default=0)),
                ('intellect_current', models.IntegerField(default=10)),
                ('intellect_pool', models.IntegerField(default=10)),
                ('intellect_edge', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('recovery_roll', models.IntegerField(default=1, verbose_name='Recovery roll 1d6+')),
                ('impaired', models.BooleanField(default=False)),
                ('debilitated', models.BooleanField(default=False)),
                ('one_action', models.BooleanField(default=False)),
                ('ten_minutes', models.BooleanField(default=False)),
                ('one_hour', models.BooleanField(default=False)),
                ('ten_hours', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Descriptor')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Focus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cypher',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
