# Generated by Django 2.0.7 on 2018-07-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0054_auto_20180721_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Genre'),
        ),
    ]
