# Generated by Django 2.0.7 on 2018-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0055_character_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(to='cyphercore.Ability'),
        ),
    ]
