# Generated by Django 2.0.7 on 2018-07-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0056_character_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('T', 'Trained'), ('S', 'Specialized'), ('I', 'Inability')], default='T', max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Skill')),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_level', 'skill__name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='cyphercore.CharacterSkill', to='cyphercore.Skill'),
        ),
    ]
