# Generated by Django 2.0.7 on 2018-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0058_auto_20180721_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='portrait_link',
            field=models.URLField(blank=True),
        ),
    ]
