# Generated by Django 2.0.7 on 2018-07-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0059_character_portrait_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Equipment')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment__name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(through='cyphercore.CharacterEquipment', to='cyphercore.Equipment'),
        ),
    ]
