# Generated by Django 2.0.7 on 2018-07-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0061_auto_20180722_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactercypher',
            options={'ordering': ['cypher__name'], 'verbose_name_plural': 'Cyphers'},
        ),
    ]
