# Generated by Django 2.0.7 on 2018-07-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0062_auto_20180722_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Artifact')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
            ],
            options={
                'verbose_name_plural': 'Artifacts',
                'ordering': ['artifact__name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='artifacts',
            field=models.ManyToManyField(through='cyphercore.CharacterArtifact', to='cyphercore.Artifact'),
        ),
    ]
