# Generated by Django 2.0.7 on 2018-07-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0063_auto_20180722_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='prefix',
            field=models.CharField(default='a', max_length=5),
        ),
    ]
