# Generated by Django 2.0.7 on 2018-07-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0064_descriptor_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='usage',
            field=models.CharField(choices=[('Action', 'Action'), ('Enabler', 'Enabler'), ('Special', 'Special')], default='Action', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
