# Generated by Django 2.0.7 on 2018-07-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0065_auto_20180724_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Genre'),
        ),
    ]
