# Generated by Django 2.0.7 on 2018-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0066_auto_20180724_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Other', 'Other')], max_length=30),
        ),
    ]
