# Generated by Django 2.0.7 on 2018-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0067_auto_20180724_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterequipment',
            name='cost',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
