# Generated by Django 2.0.7 on 2018-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0068_characterequipment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='genre',
        ),
        migrations.AddField(
            model_name='equipment',
            name='genre',
            field=models.ManyToManyField(to='cyphercore.Genre'),
        ),
    ]
