# Generated by Django 2.0.7 on 2018-07-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0069_auto_20180724_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='genre',
        ),
    ]
