# Generated by Django 2.0.7 on 2018-07-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0070_remove_equipment_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='sourcebook',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='character',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
