# Generated by Django 2.0.7 on 2018-07-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0071_auto_20180724_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
