# Generated by Django 2.0.7 on 2018-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0074_auto_20180726_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
