# Generated by Django 2.0.7 on 2018-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0075_auto_20180727_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='depletion',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
