# Generated by Django 2.0.7 on 2018-07-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0076_auto_20180727_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modifier', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
