# Generated by Django 2.0.7 on 2018-07-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0077_attack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='notes',
        ),
    ]
