# Generated by Django 2.0.7 on 2018-08-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0078_remove_attack_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name'], 'verbose_name': 'Ability', 'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['name'], 'verbose_name': 'Artifact', 'verbose_name_plural': 'Artifacts'},
        ),
        migrations.AlterModelOptions(
            name='attack',
            options={'ordering': ['name'], 'verbose_name': 'Attack', 'verbose_name_plural': 'Attacks'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='characterartifact',
            options={'ordering': ['artifact__name'], 'verbose_name': 'Artifact', 'verbose_name_plural': 'Artifacts'},
        ),
        migrations.AlterModelOptions(
            name='charactercypher',
            options={'ordering': ['cypher__name'], 'verbose_name': 'Cypher', 'verbose_name_plural': 'Cyphers'},
        ),
        migrations.AlterModelOptions(
            name='characterequipment',
            options={'ordering': ['equipment__name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='characterskill',
            options={'ordering': ['-skill_level', 'skill__name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='cypher',
            options={'ordering': ['name'], 'verbose_name': 'Cypher', 'verbose_name_plural': 'Cyphers'},
        ),
        migrations.AlterModelOptions(
            name='descriptor',
            options={'ordering': ['name'], 'verbose_name': 'Descriptor', 'verbose_name_plural': 'Descriptors'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='focus',
            options={'ordering': ['name'], 'verbose_name': 'Focus', 'verbose_name_plural': 'Foci'},
        ),
        migrations.AlterModelOptions(
            name='focusability',
            options={'ordering': ['tier', 'ability__name'], 'verbose_name': 'Focus Ability', 'verbose_name_plural': 'Focus Abilities'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='sourcebook',
            options={'ordering': ['name'], 'verbose_name': 'Sourcebook', 'verbose_name_plural': 'Sourcebooks'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'Type', 'verbose_name_plural': 'Type'},
        ),
        migrations.AlterModelOptions(
            name='typeability',
            options={'ordering': ['tier', 'ability__name'], 'verbose_name': 'Type Ability', 'verbose_name_plural': 'Type Abilities'},
        ),
    ]
