# Generated by Django 2.0.7 on 2018-08-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0080_remove_sourcebook_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='cyphercore.Ability'),
        ),
    ]
