# Generated by Django 2.1 on 2018-08-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0087_auto_20180814_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='tier_1_effor',
            new_name='tier_1_effort',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tier_2_effor',
            new_name='tier_2_effort',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tier_3_effor',
            new_name='tier_3_effort',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tier_4_effor',
            new_name='tier_4_effort',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tier_5_effor',
            new_name='tier_5_effort',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tier_6_effor',
            new_name='tier_6_effort',
        ),
    ]
