# Generated by Django 2.1 on 2018-08-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0088_auto_20180814_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abilities',
        ),
    ]
