# Generated by Django 2.1 on 2018-08-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0089_remove_character_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_note', models.CharField(blank=True, max_length=50)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
                'ordering': ['ability__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(through='cyphercore.CharacterAbility', to='cyphercore.Ability'),
        ),
    ]
