# Generated by Django 2.1 on 2018-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0091_auto_20180818_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterability',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
