# Generated by Django 2.1.3 on 2018-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0096_auto_20181129_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='movement',
            field=models.CharField(max_length=500),
        ),
    ]
