# Generated by Django 2.1.3 on 2018-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0097_auto_20181129_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='creature',
            name='gm_intrusion',
            field=models.TextField(blank=True, verbose_name='GM intrusion'),
        ),
    ]
