# Generated by Django 2.1.3 on 2018-11-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0098_auto_20181129_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='portrait_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
