# Generated by Django 2.1.3 on 2019-01-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0099_creature_portrait_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['display_name'],
                'verbose_name': 'Player',
                'abstract': False,
                'verbose_name_plural': 'Players',
            },
        ),
    ]
