# Generated by Django 2.1.3 on 2019-01-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0101_character_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='password123', max_length=128),
            preserve_default=False,
        ),
    ]
