# Generated by Django 2.1.3 on 2019-01-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0103_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Player'),
        ),
    ]
