# Generated by Django 2.1.3 on 2019-01-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0104_auto_20190108_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Player'),
            preserve_default=False,
        ),
    ]
