# Generated by Django 2.1.3 on 2019-01-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0105_auto_20190108_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Player', verbose_name='GM'),
        ),
    ]
