# Generated by Django 2.1.3 on 2019-01-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0106_auto_20190109_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Character')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Campaign Character',
                'ordering': ['character__name'],
                'verbose_name_plural': 'Campaign Characters',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(through='cyphercore.CampaignCharacter', to='cyphercore.Character'),
        ),
    ]
