# Generated by Django 2.1.3 on 2019-01-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0107_auto_20190109_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncharacter',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigncharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Campaign'),
        ),
        migrations.DeleteModel(
            name='CampaignCharacter',
        ),
    ]
