# Generated by Django 2.1.5 on 2019-01-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0116_auto_20190114_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='gm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyphercore.Player', verbose_name='GM'),
        ),
    ]
