# Generated by Django 2.1.7 on 2019-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0124_auto_20190221_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='imparts_skills',
            field=models.TextField(blank=True),
        ),
    ]
