# Generated by Django 2.1.7 on 2019-07-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0125_ability_imparts_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='imparts_skills',
            field=models.TextField(blank=True),
        ),
    ]
