# Generated by Django 2.1.7 on 2019-07-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0126_type_imparts_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='imparts_skills',
        ),
        migrations.AddField(
            model_name='ability',
            name='imparts_skills',
            field=models.ManyToManyField(to='cyphercore.Skill'),
        ),
    ]
