# Generated by Django 2.0.7 on 2018-08-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyphercore', '0078_remove_attack_notes'),
        ('numenera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage', models.CharField(choices=[('Action', 'Action'), ('Enabler', 'Enabler'), ('Special', 'Special')], default='Action', max_length=10)),
                ('cost', models.CharField(default='-', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('sourcebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook')),
            ],
            options={
                'verbose_name_plural': 'Abilities',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='descriptor name')),
                ('prefix', models.CharField(default='a', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('characteristics', models.TextField(blank=True)),
                ('starting_link', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('sourcebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Other', 'Other')], max_length=30)),
                ('base_cost', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('sourcebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cyphercore.Sourcebook')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nSourcebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='sourcebook')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='nSkill',
        ),
    ]
