# Generated by Django 2.0.7 on 2018-08-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0003_auto_20180801_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsourcebook',
            name='enabled',
        ),
    ]
