# Generated by Django 2.0.7 on 2018-08-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0004_remove_nsourcebook_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndescriptor',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.nSourcebook'),
        ),
    ]
