# Generated by Django 2.0.7 on 2018-08-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0005_auto_20180801_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nequipment',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.nSourcebook'),
        ),
    ]
