# Generated by Django 2.0.7 on 2018-08-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0006_auto_20180801_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nability',
            name='sourcebook',
        ),
        migrations.RemoveField(
            model_name='ndescriptor',
            name='sourcebook',
        ),
        migrations.RemoveField(
            model_name='nequipment',
            name='sourcebook',
        ),
        migrations.DeleteModel(
            name='nSkill',
        ),
        migrations.DeleteModel(
            name='nAbility',
        ),
        migrations.DeleteModel(
            name='nDescriptor',
        ),
        migrations.DeleteModel(
            name='nEquipment',
        ),
        migrations.DeleteModel(
            name='nSourcebook',
        ),
    ]
