# Generated by Django 2.0.7 on 2018-08-02 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numenera', '0007_auto_20180801_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage', models.CharField(choices=[('Action', 'Action'), ('Enabler', 'Enabler'), ('Special', 'Special')], default='Action', max_length=10)),
                ('cost', models.CharField(default='-', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level_range', models.CharField(max_length=10)),
                ('form', models.TextField()),
                ('effect', models.TextField()),
                ('depletion', models.CharField(default='-', max_length=20)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level_range', models.CharField(max_length=10)),
                ('effect', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Cypher',
                'verbose_name_plural': 'Cyphers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='descriptor name')),
                ('prefix', models.CharField(default='a', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('characteristics', models.TextField(blank=True)),
                ('starting_link', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Descriptor',
                'verbose_name_plural': 'Descriptors',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Armor', 'Armor'), ('Weapon', 'Weapon'), ('Other', 'Other')], max_length=30)),
                ('base_cost', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('connections', models.TextField(blank=True)),
                ('other_details', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Focus',
                'verbose_name_plural': 'Foci',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numenera.Ability')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numenera.Focus')),
            ],
            options={
                'verbose_name': 'Focus Ability',
                'verbose_name_plural': 'Focus Abilities',
                'ordering': ['tier', 'ability__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sourcebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='sourcebook')),
            ],
            options={
                'verbose_name': 'Sourcebook',
                'verbose_name_plural': 'Sourcebooks',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='type name')),
                ('might_pool', models.IntegerField(default=10)),
                ('might_edge', models.IntegerField(default=0)),
                ('speed_pool', models.IntegerField(default=10)),
                ('speed_edge', models.IntegerField(default=0)),
                ('intellect_pool', models.IntegerField(default=10)),
                ('intellect_edge', models.IntegerField(default=0)),
                ('effort', models.IntegerField(default=1)),
                ('cypher_limit', models.IntegerField(default=2)),
                ('pool_points', models.IntegerField(default=6)),
                ('description', models.TextField(blank=True)),
                ('base_abilities', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(default=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numenera.Ability')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numenera.Type')),
            ],
            options={
                'verbose_name': 'Type Ability',
                'verbose_name_plural': 'Type Abilities',
                'ordering': ['tier', 'ability__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='type',
            name='abilities',
            field=models.ManyToManyField(through='numenera.TypeAbility', to='numenera.Ability'),
        ),
        migrations.AddField(
            model_name='type',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities',
            field=models.ManyToManyField(through='numenera.FocusAbility', to='numenera.Ability'),
        ),
        migrations.AddField(
            model_name='focus',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='cypher',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
        migrations.AddField(
            model_name='ability',
            name='sourcebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='numenera.Sourcebook'),
        ),
    ]
