# Generated by Django 2.0.7 on 2018-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0009_auto_20180802_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='numenera.Ability'),
        ),
    ]
