# Generated by Django 2.0.7 on 2018-08-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0010_auto_20180802_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oddity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numenera.Character')),
            ],
            options={
                'verbose_name': 'Oddity',
                'verbose_name_plural': 'Oddities',
                'ordering': ['description'],
            },
        ),
    ]
