# Generated by Django 2.0.7 on 2018-08-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0011_oddity'),
        ('numenera', '0011_auto_20180805_0609'),
    ]

    operations = [
    ]
