# Generated by Django 2.1.5 on 2019-01-14 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0026_remove_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='access_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
