# Generated by Django 2.1.5 on 2019-01-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0029_auto_20190114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
