# Generated by Django 2.1.5 on 2019-01-15 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('numenera', '0034_auto_20190115_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
