# Generated by Django 2.0.7 on 2018-08-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0003_auto_20180805_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portrait_link', models.URLField(blank=True)),
                ('money', models.IntegerField(default=0)),
                ('might_pool_adjust', models.IntegerField(default=0)),
                ('might_edge_adjust', models.IntegerField(default=0)),
                ('speed_pool_adjust', models.IntegerField(default=0)),
                ('speed_edge_adjust', models.IntegerField(default=0)),
                ('intellect_pool_adjust', models.IntegerField(default=0)),
                ('intellect_edge_adjust', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('abilities', models.ManyToManyField(to='strange.Ability')),
            ],
            options={
                'verbose_name': 'Character Recursion',
                'verbose_name_plural': 'Character Recursions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecursionArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Artifact')),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['artifact__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecursionEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Equipment')),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecursionSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('T', 'Trained'), ('S', 'Specialized'), ('I', 'Inability')], default='T', max_length=1)),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-skill_level', 'skill__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recursion',
            name='artifacts',
            field=models.ManyToManyField(through='strange.RecursionArtifact', to='strange.Artifact'),
        ),
        migrations.AddField(
            model_name='recursion',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Character'),
        ),
        migrations.AddField(
            model_name='recursion',
            name='equipment',
            field=models.ManyToManyField(through='strange.RecursionEquipment', to='strange.Equipment'),
        ),
        migrations.AddField(
            model_name='recursion',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strange.Focus'),
        ),
        migrations.AddField(
            model_name='recursion',
            name='skills',
            field=models.ManyToManyField(through='strange.RecursionSkill', to='strange.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='recursion',
            unique_together={('character', 'name')},
        ),
    ]
