# Generated by Django 2.0.7 on 2018-08-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0004_auto_20180805_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modifier', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Character')),
            ],
            options={
                'verbose_name': 'Attack',
                'verbose_name_plural': 'Attacks',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Artifact')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Character')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['artifact__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Character')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Equipment')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment__name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recursionartifact',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='recursionartifact',
            name='recursion',
        ),
        migrations.RemoveField(
            model_name='recursionequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='recursionequipment',
            name='recursion',
        ),
        migrations.RemoveField(
            model_name='recursionskill',
            name='recursion',
        ),
        migrations.RemoveField(
            model_name='recursionskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='recursion',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='recursion',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='recursion',
            name='money',
        ),
        migrations.AddField(
            model_name='characterskill',
            name='recursion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursion',
            name='artifacts',
            field=models.ManyToManyField(through='strange.CharacterArtifact', to='strange.Artifact'),
        ),
        migrations.AlterField(
            model_name='recursion',
            name='equipment',
            field=models.ManyToManyField(through='strange.CharacterEquipment', to='strange.Equipment'),
        ),
        migrations.AlterField(
            model_name='recursion',
            name='skills',
            field=models.ManyToManyField(through='strange.CharacterSkill', to='strange.Skill'),
        ),
        migrations.DeleteModel(
            name='RecursionArtifact',
        ),
        migrations.DeleteModel(
            name='RecursionEquipment',
        ),
        migrations.DeleteModel(
            name='RecursionSkill',
        ),
        migrations.AddField(
            model_name='characterequipment',
            name='recursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
        migrations.AddField(
            model_name='characterartifact',
            name='recursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
        migrations.AddField(
            model_name='attack',
            name='recursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
    ]
