# Generated by Django 2.0.7 on 2018-08-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0005_auto_20180805_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursion',
            name='portrait_link',
        ),
        migrations.AddField(
            model_name='recursion',
            name='focus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='strange.Focus'),
            preserve_default=False,
        ),
    ]
