# Generated by Django 2.0.7 on 2018-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0006_auto_20180805_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursion',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
