# Generated by Django 2.0.7 on 2018-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0007_recursion_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursion',
            name='armor',
            field=models.IntegerField(default=0),
        ),
    ]
