# Generated by Django 2.0.7 on 2018-08-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0010_auto_20180805_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='recursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
    ]
