# Generated by Django 2.0.7 on 2018-08-05 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0011_auto_20180805_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='recursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
        migrations.AlterField(
            model_name='characterartifact',
            name='recursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='recursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
        ),
    ]
