# Generated by Django 2.0.7 on 2018-08-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0013_auto_20180805_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterartifact',
            options={'ordering': ['recursion__name', 'artifact__name'], 'verbose_name': 'Artifact', 'verbose_name_plural': 'Artifacts'},
        ),
        migrations.AlterModelOptions(
            name='characterequipment',
            options={'ordering': ['recursion__name', 'equipment__name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='characterskill',
            options={'ordering': ['recursion__name', '-skill_level'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='cypher',
            name='form',
            field=models.TextField(default='Form'),
            preserve_default=False,
        ),
    ]
