# Generated by Django 2.0.7 on 2018-08-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0016_auto_20180805_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterField(
            model_name='ability',
            name='cost',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
