# Generated by Django 2.1 on 2018-08-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0020_auto_20180806_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterequipment',
            name='cost',
        ),
        migrations.AddField(
            model_name='characterequipment',
            name='brief_note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
