# Generated by Django 2.1 on 2018-08-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0025_auto_20180818_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursionAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Ability')),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
                'ordering': ['ability__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recursion',
            name='abilities',
            field=models.ManyToManyField(through='strange.RecursionAbility', to='strange.Ability'),
        ),
    ]
