# Generated by Django 2.1 on 2018-08-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0026_auto_20180818_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursion',
            options={'ordering': ['character', 'name'], 'verbose_name': 'Recursion', 'verbose_name_plural': 'Recursions'},
        ),
        migrations.AddField(
            model_name='recursion',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
