# Generated by Django 2.1 on 2018-08-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0027_auto_20180819_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterability',
            options={'ordering': ['ability__name'], 'verbose_name': 'Global Ability', 'verbose_name_plural': 'Global Abilities'},
        ),
    ]
