# Generated by Django 2.1 on 2018-08-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0027_auto_20180819_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterability',
            options={'ordering': ['ability__name'], 'verbose_name': 'Global Ability', 'verbose_name_plural': 'Global Abilities'},
        ),
        migrations.RemoveField(
            model_name='characterequipment',
            name='character',
        ),
        migrations.AddField(
            model_name='recursion',
            name='equipment',
            field=models.ManyToManyField(through='strange.CharacterEquipment', to='strange.Equipment'),
        ),
        migrations.AlterField(
            model_name='characterability',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='characterequipment',
            name='recursion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recursionability',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
