# Generated by Django 2.1 on 2018-08-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0029_remove_characterskill_recursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursionSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('T', 'Trained'), ('S', 'Specialized'), ('I', 'Inability')], default='T', max_length=1)),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-skill_level'],
            },
        ),
        migrations.AlterModelOptions(
            name='characterskill',
            options={'ordering': ['-skill_level'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='recursion',
            name='skills',
            field=models.ManyToManyField(through='strange.RecursionSkill', to='strange.Skill'),
        ),
    ]
