# Generated by Django 2.1 on 2018-08-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0031_auto_20180819_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterartifact',
            options={'ordering': ['artifact__name'], 'verbose_name': 'Artifact', 'verbose_name_plural': 'Artifacts'},
        ),
        migrations.RemoveField(
            model_name='characterartifact',
            name='character',
        ),
        migrations.AlterField(
            model_name='attack',
            name='recursion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterartifact',
            name='recursion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion'),
            preserve_default=False,
        ),
    ]
