# Generated by Django 2.1 on 2018-08-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0028_auto_20180819_0340'),
        ('strange', '0032_auto_20180819_0317'),
    ]

    operations = [
    ]
