# Generated by Django 2.1 on 2018-08-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0033_merge_20180819_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modifier', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attack',
            options={'ordering': ['name']},
        ),
    ]
