# Generated by Django 2.1 on 2018-08-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0034_auto_20180819_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursionAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modifier', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('recursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strange.Recursion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='characterattack',
            name='character',
        ),
        migrations.RemoveField(
            model_name='attack',
            name='recursion',
        ),
        migrations.AddField(
            model_name='attack',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strange.Character'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterAttack',
        ),
    ]
