# Generated by Django 2.1.3 on 2018-12-31 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strange', '0037_auto_20181003_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('portrait_link', models.URLField(blank=True, max_length=1000)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=3)),
                ('damage_inflicted', models.CharField(max_length=50)),
                ('armor', models.IntegerField(default=0)),
                ('motive', models.CharField(max_length=500)),
                ('environment', models.CharField(max_length=500)),
                ('movement', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('modifications', models.TextField(blank=True)),
                ('combat', models.TextField(blank=True)),
                ('interaction', models.TextField(blank=True)),
                ('use', models.TextField(blank=True)),
                ('loot', models.TextField(blank=True)),
                ('gm_intrusion', models.TextField(blank=True, verbose_name='GM intrusion')),
                ('sourcebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='strange.Sourcebook')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Creature',
                'verbose_name_plural': 'Creatures',
                'ordering': ['name'],
            },
        ),
    ]
